#ifndef SIMPLEOPERATION_GLOBAL_H
#define SIMPLEOPERATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMPLEOPERATION_LIBRARY)
#  define SIMPLEOPERATION_EXPORT Q_DECL_EXPORT
#else
#  define SIMPLEOPERATION_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMPLEOPERATION_GLOBAL_H
